<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <AssemblyName>VirusTotalNet.v3</AssemblyName>
    <RootNamespace>VirusTotalNet.v3</RootNamespace>
    <PackageId>VirusTotalNet.v3</PackageId>
    <Version>0.1.0-alpha</Version>
    <Authors>Tran T. Ngoc</Authors>
    <Description>A modern .NET client for the VirusTotal API v3. Strongly-typed yet lossless, rate-limit aware, zero external dependencies.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <RepositoryUrl>https://github.com/zymuk/VirusTotalNetv3.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsTrimmable>true</IsTrimmable>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

</Project>